name: intro pipeline

on:
  workflow_dispatch:

jobs:
  basic-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: second step
        run: |
          ls -la
          cat testo.txt